"""Worker-prompt generation.

Given a valid work order, render a self-contained Claude Code *worker prompt*
markdown file under ``outputs/operator_control/prompts/{work_order_id}.md``.

The prompt is a CONTRACT for a future worker: it states the issue, the exact
source artifacts to inspect, the selected skill, the allowed and forbidden
actions, the required tests, the expected output report path, and the
observe-only / no-trade constraints. Generating the prompt writes a file — it
does NOT execute anything.
"""
from __future__ import annotations

from pathlib import Path

from operator_control import prompt_path, report_path
from operator_control.probe_registry import get_probe
from operator_control.skill_registry import get_skill
from operator_control import work_orders as wo

# Project contracts/runbooks a worker MUST read before changing anything.
_REQUIRED_READING = (
    "CLAUDE.md (hard boundaries, protected semantics, observe-only default)",
    "docs/ARCHITECTURE.md",
    "docs/decision_engine.md",
    "docs/OUTPUT_ARTIFACT_CONTRACTS.md",
    "docs/PIPELINE_RUNBOOK.md",
    "docs/operator_control.md (this work-order's own contract)",
)


def _bullets(items) -> str:
    return "\n".join(f"- {x}" for x in items) if items else "- (none)"


def render_prompt(root: Path | str, work_order_id: str) -> str:
    """Render and return the prompt markdown (does not write a file)."""
    order = wo.get_work_order(root, work_order_id)
    if order is None:
        raise ValueError(f"unknown work_order_id: {work_order_id!r}")

    probe = get_probe(order["probe_id"])
    skill = get_skill(order["skill_id"])
    if probe is None or skill is None:
        raise ValueError(
            f"work order {work_order_id} references an unknown probe/skill"
        )

    mode = order["mode"]
    report_rel = report_path(root, work_order_id)
    try:
        report_rel = report_rel.relative_to(Path(root))
    except (ValueError, TypeError):
        pass

    observe_notice = probe.observe_only_notice

    md = f"""# Worker Prompt — {work_order_id}

> **Observe-only work order.** {observe_notice}
> This system is advisory-only and must **never** execute trades. You are a
> repair/diagnostic worker, not a trader.

## Issue summary

{order['requested_action']}

**Probe:** `{probe.probe_id}` — {probe.display_name} (severity: {probe.severity})
{probe.description}

**Source view:** {order['source_view']}
**Selected skill:** `{skill.skill_id}` — {skill.name}
**Mode:** `{mode}`
**Risk level:** {order['risk_level']}
**Approval required before any apply:** {"YES" if order['approval_required'] else "no"}

## Source artifacts to inspect (read these; do not copy blindly)

{_bullets(order.get('source_artifacts'))}

## What this skill does

{skill.description}

## Allowed actions

{_bullets(['mode: ' + m for m in skill.allowed_modes])}

This work order authorizes **only** mode `{mode}`.
- `diagnose` — read + explain. No file changes.
- `propose_fix` — write a proposal document only. Do **not** apply it.
- `safe_repair` — a narrow, reversible change to a NON-protected artifact, gated
  by human approval and the required tests below.

## Forbidden actions (hard boundaries — do not cross)

{_bullets(skill.effective_forbidden_actions())}

## Required tests (run before reporting done)

{_bullets(skill.required_tests)}
- `python -m pytest -q` (broader suite if your change widened scope)

## Required reading BEFORE making any change

{_bullets(_REQUIRED_READING)}

## Working style

- Trace the exact source-to-artifact path before editing.
- Name exact files and functions before changing behavior.
- Make focused changes only — the smallest patch that resolves the probe.
- Keep all changes additive and backward compatible.
- If you are blocked, or a fix would require crossing a forbidden boundary,
  **stop and report** rather than working around it.
- Do not modify investment logic, scoring, broker behavior, secrets,
  dependencies, or deployment configs unless the operator explicitly approves
  that scope in a follow-up.

## Expected output report

Write your report to: `{report_rel}`

It must contain:

{_bullets(skill.output_report_requirements)}

## Safety constraints (stamped on this work order)

{_bullets(order.get('safety_constraints'))}

---
*Generated by operator_control.worker_prompts for work order {work_order_id}.*
*Generating this prompt did not execute anything; a human/worker must act on it.*
"""
    return md


def generate_prompt(
    root: Path | str, work_order_id: str, *, actor: str = "cli"
) -> Path:
    """Render the prompt, write it to disk, and record it on the work order."""
    md = render_prompt(root, work_order_id)
    out = prompt_path(root, work_order_id)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(md, encoding="utf-8")

    # Record the generated path on the work order (append-only) + audit.
    try:
        rel = str(out.relative_to(Path(root)))
    except (ValueError, TypeError):
        rel = str(out)
    wo.attach_prompt_path(root, work_order_id, rel, actor=actor)
    return out


__all__ = ["render_prompt", "generate_prompt"]
